platform :ios, '9.2'
use_modular_headers!
use_frameworks!

target 'DemoPushNotificationCocoaPod_Example' do
    pod 'DemoPushNotificationCocoaPod', :path => '../'
    pod 'AWSCore', '~> 2.7.0',:modular_headers => true
    pod  'AWSPinpoint', '~> 2.7.0',:modular_headers => true
    pod  'AWSMobileClient', '~> 2.7.0',:modular_headers => true
    
    target 'DemoPushNotificationCocoaPod_Tests' do
        inherit! :search_paths
        
        
    end
end
