use_frameworks!

target 'DemoPushNotificationCocoaPod_Example' do
  pod 'DemoPushNotificationCocoaPod', :path => '../'

  target 'DemoPushNotificationCocoaPod_Tests' do
    inherit! :search_paths

    
  end
end
